import { FloorModel } from "../../../types/floor/floor.type";

export const HD_floorList: FloorModel[] = [
  {
    id: "1-1",
    createdAt: "",
    updatedAt: "",
    floorLevel: 1,
    houseId: "1",
    roomsCount: 4,
    devicesCount: 20,
    powerUsedInDay: 10,
    powerUsedInWeek: 22,
    powerUsedInMonth: 40,
  },
  {
    id: "1-2",
    createdAt: "",
    updatedAt: "",
    floorLevel: 2,
    houseId: "1",
    roomsCount: 3,
    devicesCount: 20,
    powerUsedInDay: 6,
    powerUsedInWeek: 10,
    powerUsedInMonth: 20,
  },
  {
    id: "1-3",
    createdAt: "",
    updatedAt: "",
    floorLevel: 3,
    houseId: "1",
    roomsCount: 1,
    devicesCount: 4,
    powerUsedInDay: 0.2,
    powerUsedInWeek: 2,
    powerUsedInMonth: 5,
  },
];
